name: forge-cms
services:
  backend:
    build:
      context: backend
    environment:
      - ADDRESS=0.0.0.0:8000
      - RUST_LOG=debug
      - PG_DBNAME=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=mysecretpassword
    networks:
      - server-side
    volumes:
      - ./backend/src:/code/src
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - server-side
    ports:
      - 5432:5432

networks:
  server-side: {}
