[package]
name = "forgecms"
version = "0.1.0"
edition = "2021"
author = ["Valentin Vareskic <valentin.vareskic@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
