name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Clippy
      run: |
        cd backend
        cargo clippy --all-targets --all-features

  build:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and run API
      run: |
        cd backend 
        ls
        cargo run &
        cargo test --verbose
