name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-build:
    name: Format & Lint
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - name: Format and Lint
      run: |
        cd ./backend
        cargo fmt
        cargo check
        cargo clippy

  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: rustup component add clippy
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

  build:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and run API
      run: |
        cd backend 
        ls
        cargo run &

    - name: Run tests
      run: |
        cd ./backend 
        cargo test --verbose
