name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Go to backend
      run: cd backend 
      run: ls
    - name: Build and run API
      run: cd ./backend & cargo run --verbose
    - name: Run tests
      run: cd ./backend & cargo test --verbose
