name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Clippy
      run: |
        cd backend
        cargo clippy --all-targets --all-features

  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: mysecretpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Migrate Database
      env:
        DATABASE_URL: postgres://postgres:mysecretpassword@localhost:5432
      run: |
        cd backend
        cargo install sqlx-cli --features postgres
        sqlx migrate run
    - name: Build and run API
      env:
        DATABASE_URL: postgres://postgres:mysecretpassword@localhost:5432
      run: |
        cd backend 
        cargo build 
        cargo sqlx prepare
        cargo run & 
        cargo test
